### ISSUE TITLE
Android MPL 1.5.6_54 rejected by Google Play

### ISSUE THREAD

**Issue by josemedaglia** [paypal/sdk-packages#72]
I'm trying to submit an update for an App but its being rejected by Google Play as it violates their Malicious Behavior policy.

> Beginning May 17, 2016, Google Play will block publishing of any new apps or updates containing the unsafe implementation of the interface X509TrustManager.

I've tested removing PayPal MPL and submit an update and it is properly processed by Google Play.

This is the vulnerability reported when submitting the app:

> 
> **Vulnerability**
> _**TrustManager**_
> 
> To properly handle SSL certificate validation, change your code in the [checkServerTrusted](https://developer.android.com/reference/javax/net/ssl/X509TrustManager.html#checkServerTrusted%28java.security.cert.X509Certificate[],%20java.lang.String%29) method of your custom X509TrustManager interface to raise either [CertificateException](http://developer.android.com/reference/java/security/cert/CertificateException.html) or [IllegalArgumentException](http://developer.android.com/reference/java/lang/IllegalArgumentException.html) whenever the certificate presented by the server does not meet your expectations. To confirm you’ve updated correctly, submit the updated version to the Developer Console and check back after five hours. If the app hasn’t been correctly upgraded, we will display a warning.
> 
> For additional information and next steps, please see this [Google Help Center](https://support.google.com/faqs/answer/6346016) article.

**Comment by juanmartincontreras** [comment]
I'm facing the same problem, please update!

**Comment by colinsupko** [comment]
This is a problem for my App as well. This needs to be brought to PayPal Attention

**Comment by pp-randy** [comment]
I have reached out to our SDK team for further assistance with this issue.

**Comment by colinsupko** [comment]
@pp-randy 

some additional data brother

Implementation
We used PayPal's official libraries account to implement Chained Payments. 

https://github.com/paypal/PayPal-Android-SDK

If you check the readme on the link, it says: 

PayPal is in the process of replacing the older "Mobile Payments Libraries" (MPL) with the new PayPal Android and iOS SDKs. The new Mobile SDKs are based on the PayPal REST API, while the older MPL uses the Adaptive Payments API.
 
Until features such as third-party, parallel, and chained payments are available, if needed, you can use MPL

To implement Chained Payments, we have to use a legacy library also provided by PayPal UNTIL they migrate the chained payments to the new Android or iOS SDKs. 

This is the library they mention on the readme, also provided by paypal.

https://github.com/paypal/sdk-packages

Current Issue

Google is rejecting builds because https://github.com/paypal/sdk-packages legacy library implementing methods with known vulnerabilities. AND it's the only library they document to handle split payments.

We subscribed already to the issue reported by another user

https://github.com/paypal/sdk-packages/issues/72

**Comment by pp-randy** [comment]
For internal tracking: PPPLMER-14952

**Comment by dawasserman** [comment]
Any updates on this? I hear lots of people having the same issue. 
Thanks!

**Comment by jaypatel512** [comment]
Hey All,

I have made a new release, that should fix this issue. However, do let me know if for any reason, Google Play throws any other vulnerability issues.

**Comment by colinsupko** [comment]
@jaypatel512 Thanks brother! we are going to check it and get back to you!

**Comment by josemedaglia** [comment]
I can confirm that the issue has been fixed.

Thank you for quickly addressing this issue.
